# Site settings
title: Chad Fawcett | Blog
email: chad@ntsstudios.com
description: This is my blog. It is set up using Jekyll and hosted for free on GitHub Pages.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chadfawcett.github.io" # the base hostname & protocol for your site
twitter_username: chadfawcett_10
github_username:  chadfawcett

# Build settings
markdown: kramdown
kramdown:
  input: GFM