# Site settings
title:       Chad Fawcett
email:       me@chadf.ca
author:      Chad Fawcett
description: "A personal blog about my projects and traveling expeditions."
baseurl:     ""
url:         "http://chadf.ca"

# collections
collections:
  oss_contributions:
    order:
      - storybook.md
      - gatsby.md
      - tickbin.md
      - facebook.md
      - bcgov.md

# Google analytics
google_analytics:

# Social icons
instagram_username: chadfawcett
github_username: chadfawcett
twitter_username: chadfawcett_10
linkedin_username: chad-fawcett

# Build settings
permalink:    pretty
sass:
  compressed: true
